/*
 * This source file was generated by the Gradle 'init' task
 */
package mx.unam.ciencias.myp

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

import mx.unam.ciencias.myp.messages.*
import mx.unam.ciencias.myp.messages.Invitation
import mx.unam.ciencias.myp.sockets.SocketClient

fun main() = application {
    Window(onCloseRequest = ::exitApplication, title = "Xerces Client") {
        screenManager()
    }
}

enum class Screens {
    Connection,Chat
}

@Composable
fun screenManager() {
    var currentScreen by remember { mutableStateOf(Screens.Connection) }

    var connectedIp by remember { mutableStateOf("") }
    var connectedPort by remember { mutableStateOf(0) }
    var currentUsername by remember { mutableStateOf("") }
    var connectionError by remember { mutableStateOf("") }

    var messages = remember { mutableStateListOf<String>() }
    var users = remember { mutableStateMapOf<String,String>() }
    var client by remember { mutableStateOf<SocketClient?>(null) }

    var privateConvo = remember { mutableStateMapOf<String,MutableList<String>>() }
    var roomConvo = remember { mutableStateMapOf<String,MutableList<String>>() }

    var roomCreationStatus by remember { mutableStateOf<RoomCreationStatus>(RoomCreationStatus.Idle) }
    
    var currentRoomUsers = remember { mutableStateMapOf<String,String>() }

    var pendingInvitations = remember { mutableStateListOf<Invitation>() }

    DisposableEffect(client) {
        val activeClient = client
        onDispose { activeClient?.close() }
    }

    when(currentScreen) {
        Screens.Connection -> {
            ConnectionWindow(
                connectionError = connectionError,
                onConnect = { ip, port, username ->
                    client = SocketClient(
                        ip = ip,
                        port = port,
                        username = username,
                        onConnected = {
                            connectedIp = ip
                            connectedPort = port
                            currentUsername = username
                            messages.clear()
                            currentScreen = Screens.Chat
                        },
                        onMessageReceived = { message->
                            val incoming = runCatching {json.decodeFromString<Message>(message)}.getOrNull()
                            determineActionFromJSON(
                                messageJSON = incoming,
                                users = users,
                                messages = messages,
                                privateConvos = privateConvo,
                                roomConvos = roomConvo,
                                onRoomStatusChange = { status-> roomCreationStatus = status },
                                roomUsers = currentRoomUsers,
                                pendingInvitations = pendingInvitations
                            )
                        },
                        onDisconnected = { error ->
                            connectionError = error
                            client = null
                            messages.clear()
                            users.clear()
                            privateConvo.clear()
                            roomConvo.clear()
                            currentRoomUsers.clear()
                            pendingInvitations.clear()
                            currentScreen = Screens.Connection
                        }
                    ).also { it.connect() }
                }
            )
        }
        Screens.Chat -> {
            LaunchedEffect(client) {
                client?.send(getFetchUserListRequest())
            }
            Chat(
                ip = connectedIp,
                port = connectedPort,
                username = currentUsername,
                messages = messages,
                users = users,
                privateConvos = privateConvo,
                roomConvos = roomConvo,
                onSend = {text, toUser, toRoom ->
                    val jsonRequest: String
                    if(toUser != null){
                        jsonRequest = json.encodeToString(Message(type = "TEXT",text = text, username = toUser))
                        val updatedMessages = privateConvo.get(toUser)?.toMutableList() ?: mutableListOf()
                        updatedMessages.add("$currentUsername: $text")
                        privateConvo.put(toUser,updatedMessages)
                    } else if(toRoom != null){
                        jsonRequest = json.encodeToString(Message(type = "ROOM_TEXT", roomname = toRoom, text = text))
                        val updatedMessages = roomConvo.get(toRoom)?.toMutableList() ?: mutableListOf()
                        updatedMessages.add("$currentUsername: $text")
                        roomConvo.put(toRoom,updatedMessages)
                    } else {
                        jsonRequest = json.encodeToString(Message(type = "PUBLIC_TEXT",text = text))
                        messages.add("$currentUsername: $text")
                    }
                    client?.send(jsonRequest)
                },
                onLeave = {
                    client?.send(getDisconnectRequest())
                    client = null
                    messages.clear()
                    users.clear()
                    privateConvo.clear()
                    roomConvo.clear()
                    currentRoomUsers.clear()
                    pendingInvitations.clear()
                    currentScreen = Screens.Connection
                },
                roomCreationStatus = roomCreationStatus,
                onNewRoom = { roomname ->
                    roomCreationStatus = RoomCreationStatus.Pending(roomname)
                    val jsonRequest = json.encodeToString(Message(type = "NEW_ROOM", roomname = roomname))
                    client?.send(jsonRequest)
                },
                onRoomInvite = { roomname, usersToInvite ->
                    val jsonRequest = json.encodeToString(Message(type = "INVITE", roomname = roomname, usernames = usersToInvite))
                    client?.send(jsonRequest)
                },
                roomUsers = currentRoomUsers,
                onRoomUsersRequest = {roomname ->
                    client?.send(getFetchRoomUserListRequest(roomname))
                } ,
                pendingInvitations = pendingInvitations,
                onAcceptInvitation = { roomname ->
                    client?.send(getJoinRoomRequest(roomname))
                },
                onDeclineInvitation = { invitation ->
                    // El protocolo no tiene un mensaje de rechazar invitación, pero se descarta localmente.
                    pendingInvitations.remove(invitation)
                },
                onLeaveRoom = { roomname ->
                    client?.send(getLeaveRoomRequest(roomname))
                    // Se retira la sala localmente de forma optimista.
                    roomConvo.remove(roomname)
                    currentRoomUsers.clear()
                }
            )
        }
    }
}  
